# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  myvars,
  ...
}: {
  wsl.enable = true;
  wsl.defaultUser = myvars.username;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
